version: 2
jobs:
  release:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout

      - run:
          name: Create a Virtualenv
          command: |
            python -m virtualenv ../venv

      - run:
          name: Install dependencies
          command: |
            . ../venv/bin/activate
            pip install twine setuptools_scm

      - run:
          name: Build the sdist
          command: |
            . ../venv/bin/activate
            python setup.py sdist

      - run:
          name: Release
          command: |
            . ../venv/bin/activate
            twine upload dist/*


workflows:
  version: 2
  ci:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
